import { ItemSolicitacaoCompraRateio } from '@shared/models/solicitacao-compra/item-solicitacao-compra-rateio';
import { SlaItem, Usuario } from '..';
import { Arquivo } from '../arquivo';
import { SituacaoSolicitacaoItemCompra } from '../enums/situacao-solicitacao-item-compra';
import { PedidoItem } from '../pedido/pedido-item';
import { PessoaJuridica } from '../pessoa-juridica';
import { RequisicaoItem } from '../requisicao/requisicao-item';
import { ItemSolicitacaoCompraComentario } from './item-solicitacao-compra-comentario';
import { SolicitacaoCompra } from './solicitacao-compra';
import { SubItemSolicitacaoCompra } from './sub-item-solicitacao-compra';

export class ItemSolicitacaoCompra {
  public idItemSolicitacaoCompra: number;
  public idTenant: number;
  public codigo: number;
  public situacao: SituacaoSolicitacaoItemCompra;
  public idSolicitacaoCompra: number;
  public codigoSolicitacaoCompra: string;
  public descricao: string;
  public codigoComprador: string;
  public codigoContrato: number;
  public infoRequisitante: string;
  public nomeProduto: string;
  public descricaoProduto: string;
  public codigoProduto: string;
  public tipoProduto: string;
  public utilizacaoProduto: string;
  public codigoOrigemProduto: string;
  public ncm: string;
  public codigoFilialEmpresa: string;
  public codigoEmpresa: string;
  public codigoDeposito: string;
  public codigoCategoria: string;
  public nomeCategoria: string;
  public quantidade: number;
  public siglaUnidadeMedida: string;
  public descricaoUnidadeMedida: string;
  public dataRemessa: string;
  public valorReferencia: number;
  public quantidadeUnidadesPreco: number;
  public tipoItem: string;
  public codigoClassificacaoContabil: string;
  public fornecedorFixo: string;
  public moeda: string;
  public previsaoEntregaDias: number;
  public numeroPacote: number;
  public codigoImobilizado: string;
  public subNumeroImobilizado: string;
  public nomeImobilizado: string;
  public ordem: string;
  public elementoPep: string;
  public diagramaRede: string;
  public pessoaJuridica: PessoaJuridica;
  public rateios: Array<ItemSolicitacaoCompraRateio>;
  public subItens: Array<SubItemSolicitacaoCompra>;
  public anexos: Array<Arquivo>;
  public comentarios: Array<ItemSolicitacaoCompraComentario>;
  public pedidoItem: PedidoItem;
  public requisicaoItem: RequisicaoItem;
  public solicitacaoCompra: SolicitacaoCompra;
  public fornecedor: PessoaJuridica;
  public slaItem: SlaItem;
  public dataHoraSla: Date;
  public idResponsavel?: number;
  public usuarioResponsavel: Usuario;
  public categoriaDemanda: string;
  public sla: string;
  public dataLiberacaoItem: string;
  public tipoDocumento: string;
  public nomeResponsavel: string;
}
