export enum SituacaoPedido {
  'Pré-pedido' = 1,
  'Cancelado' = 2,
  'Aguardando fornecedor' = 3,
  'Aguardando requisitante' = 5,
  'Aguardando aprovação' = 6,
  'Aprovado' = 7,
  'Confirmado' = 9,
  'Preparado' = 10,
  'Enviado' = 11,
  'Entregue' = 12,
  'Pendente integração' = 13,
  'Faturado' = 14,
  'Aguardando Pacote' = 16,
  'Cancelamento Solicitado' = 17,
  'Entregue Parcialmente' = 18,
  'Aguardando Integração Requisição' = 19,
  'Integração Requisição Cancelada' = 20,
  'Aguardando Integração' = 21,
  'Erro de Integração' = 22,
  'Aguardando Integracao API' = 23,
  'Aguardando Aprovação Externa' = 24,
}
