export enum TipoFrete {
    Cif = 1,
    Fob = 2,
    "FOB Dirigido" = 3,
    "FOB Redespacho" = 4,
    Exw = 5,
    Fca = 6,
    Cpt = 7,
    Cip = 8,
    Dat = 9,
    Dap = 10,
    Ddp = 11,
    Fas = 12,
    Cfr = 13,
    Daf = 14,
    Ddu = 15,
    Deq = 16,
    Des = 17,
    Fh = 18
}